[libjpeg-turbo] enable jpeg_mem_src/dest
sailfishos/libjpeg-turbo pull request #1
Opened 2022-08-26 18:55 UTC by attah

You'll need this for any significant update to Poppler (21.12.0 and onwards).
Sure, this is a bit iffy library-versioning-wise, but i can't see that it actually _breaks_ anything and all the cool kids are doing it.
But then again, C/C++ is not my day job.

2022-08-26 19:09 UTC, Thaodan requested changes
Please explain the change better and rather implicitly enabling it, enable it explicitly.

This way it is reproducible and it breaks once the option is removed.

2022-08-26 19:17 UTC, attah commented
What this does is make the source/destination managers (i.e. io handlers) that work with in-memory data exist at all, along side with the previous only option that handles FILE*.

See also: https://github.com/sailfishos-mirror/libjpeg-turbo/blob/a219fd13b086d9af53de37a5e1bfec985cda60fc/README.md#in-memory-sourcedestination-managers

I'm not sure i follow, there is nothing that will break if a define no longer does anything or exists inside the code, so `-DWITH_MEM_SRCDST=1` would be pointless.

2022-08-26 20:16 UTC, Thaodan commented
>What this does is make the source/destination managers (i.e. io handlers) that work with in-memory data exist at all, along side with the previous only option that handles FILE*.

Ok that sounds good, as the api isn't harbour whitelist abi breaks shouldn't matter, if we decide to preserve in abi in this case need to offer both versions.

> I'm not sure i follow, there is nothing that will break if a define no longer does anything or exists inside the code, so `-DWITH_MEM_SRCDST=1` would be pointless.

Other build systems usually exit if you specific invalid options, e.g if upstream removes or renames it something happen.
But I get it now.

2022-08-30 13:28 UTC, pvuorela commented
Needs now rebasing.

Otherwise seems good to me. Since nothing promised for this library, better to avoid sticking to old ABI.

2022-09-02 10:55 UTC, pvuorela approved these changes

2022-09-02 10:55 UTC, merged